POST http://localhost:8000/api/auth/register
content-type: application/json

{
    "firstname": "iClass",
    "lastname": "Chima",
    "email": "oga@gmail.com",
    "cohort": 3,
    "password": "iclasschima"
}

###

POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "iclasschima@gmail.com",
    "password": "iclasschima"
}

###

POST http://localhost:8000/api/user/add_project
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE4Y2JiMmQzNmE4ZDI5NGViMzU3ZmMiLCJpYXQiOjE2MDQ4OTg2ODJ9.XgcN_sOuHxin7t_C_s8UW__Dn6jEnrgYOtBRTR1mkhg
Content-Type: application/json

{
    "user_id": "5fa8cbb2d36a8d294eb357fc",
    "title": "onHover Storeman",
    "start_date": "12-11-2020"
}

###

GET http://localhost:8000/api/users
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE4Y2JiMmQzNmE4ZDI5NGViMzU3ZmMiLCJpYXQiOjE2MDQ4OTg2ODJ9.XgcN_sOuHxin7t_C_s8UW__Dn6jEnrgYOtBRTR1mkhg

###

GET http://localhost:8000/api/message/messages/5fa7c34d18d38e2545ae2182
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE4Y2JiMmQzNmE4ZDI5NGViMzU3ZmMiLCJpYXQiOjE2MDQ4OTg2ODJ9.XgcN_sOuHxin7t_C_s8UW__Dn6jEnrgYOtBRTR1mkhg


###

POST http://localhost:8000/api/message/send
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmE4Y2JiMmQzNmE4ZDI5NGViMzU3ZmMiLCJpYXQiOjE2MDQ4OTg2ODJ9.XgcN_sOuHxin7t_C_s8UW__Dn6jEnrgYOtBRTR1mkhg
Content-Type: application/json

{
    "user_id": "5fa8cb7337d20d290cd4549a",
    "reciever_id": "5fa92b1ec4d6d81a13187fb4",
    "message": "Hello iclass"
}

###